# EVE-NG Lab Configuration Template
# Copy this to testbed.yaml and update with your actual lab details
# This format is compatible with pyATS

---
# =================================================================
# EVE-NG LAB TESTBED CONFIGURATION (pyATS Format)
# =================================================================
# Instructions:
# 1. Update all IP addresses to match your EVE-NG management network
# 2. Update credentials for each device
# 3. Add/remove devices based on your actual lab topology
# 4. Test connectivity using the agent's test_connectivity_tool
# =================================================================

devices:
  # =================================================================
  # CISCO DEVICES
  # =================================================================
  
  cisco_router_main:
    alias: "Main Campus Router"
    type: "router"
    os: "iosxe"                    # or "ios" for older devices
    platform: "CSR1000v"          # CSR1000v, ISR4000, etc.
    credentials:
      default:
        username: "admin"          # Update with your device credentials
        password: "admin"          # Update with your device credentials
    connections:
      cli:
        protocol: ssh
        ip: "192.168.1.10"         # Update with your EVE-NG lab IP
        port: 22
        arguments:
          connection_timeout: 60
          
  cisco_switch_core:
    alias: "Core Distribution Switch"
    type: "switch"
    os: "iosxe"
    platform: "Cat9300"           # Cat9300, Cat3850, etc.
    credentials:
      default:
        username: "admin"
        password: "admin"
    connections:
      cli:
        protocol: ssh
        ip: "192.168.1.11"         # Update with your EVE-NG lab IP
        port: 22
        arguments:
          connection_timeout: 60

  cisco_switch_access:
    alias: "Access Layer Switch"
    type: "switch"
    os: "iosxe"
    platform: "Cat2960"
    credentials:
      default:
        username: "admin"
        password: "admin"
    connections:
      cli:
        protocol: ssh
        ip: "192.168.1.12"         # Update with your EVE-NG lab IP
        port: 22
        arguments:
          connection_timeout: 60

  # =================================================================
  # JUNIPER DEVICES (if available in your lab)
  # =================================================================
  
  juniper_router_branch:
    alias: "Branch Office Router"
    type: "router"
    os: "junos"
    platform: "vMX"               # vMX, vSRX, etc.
    credentials:
      default:
        username: "admin"          # Common: root, admin, lab
        password: "admin"          # Update with your credentials
    connections:
      cli:
        protocol: ssh
        ip: "192.168.1.20"         # Update with your EVE-NG lab IP
        port: 22
        arguments:
          connection_timeout: 60

  # =================================================================
  # ADD MORE DEVICES AS NEEDED
  # =================================================================
  # Examples for other vendors:
  #
  # arista_switch_dc:
  #   alias: "Data Center Switch"
  #   type: "switch"
  #   os: "eos"
  #   platform: "vEOS"
  #   credentials:
  #     default:
  #       username: "admin"
  #       password: "admin"
  #   connections:
  #     cli:
  #       protocol: ssh
  #       ip: "192.168.1.30"
  #       port: 22
  #       arguments:
  #         connection_timeout: 60

# =================================================================
# TOPOLOGY SECTION (pyATS compatible)
# =================================================================

topology:
  lab_name: "Multi-Vendor Lab"

# =================================================================
# NOTES:
# =================================================================
# - This is a simplified pyATS-compatible format
# - For advanced pyATS features, you can add more sections
# - The agent will work with any pyATS-compatible testbed
# - Non-Cisco devices may have limited command support
# ================================================================= 